name: update-s3-files
on:
  push:

jobs:
  update-s3-shares:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v2
      - name: Grab claat tool
        run: wget https://github.com/Noname-SA/claat-tool/releases/download/main/claat && chmod +x claat
      - name: Build prework guide
        run: ./claat export -o $(pwd)/workshop-shares/ $(pwd)/workshop-shares/guides/prework/guide.md
      - name: Build hands-on guide
        run: ./claat export -o $(pwd)/workshop-shares/ $(pwd)/workshop-shares/guides/hands-on/guide.md
      - name: Remove guides folder
        run: rm -rf workshop-shares/guides
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: 'us-east-2'
      - name: Update S3 Files
        working-directory: ./workshop-shares
        run: for FILE in *; do (test -d $FILE && zip -r $FILE.zip $FILE && aws s3 cp $FILE.zip s3://noname-workshop-share/$BRANCH/$FILE.zip) || (aws s3 cp $FILE s3://noname-workshop-share/$BRANCH/$FILE); done
        env:
          BRANCH: ${{ github.ref_name	}}
